### ISSUE TITLE
Package pdf2htmlEX as binary

### ISSUE THREAD

**Issue by TomTasche** [ViliusSutkus89/pdf2htmlEX-Android#21]
We'd like to execute the binary manually via Java or other code - without going through JNI.

We've had a conversation on that already and it didn't seem possible out of the box due to recent restrictions on Android, but it sounded like there might be possible workarounds...

**Comment by ViliusSutkus89** [comment]
OK, let's see what's possible.

I can stuff binaries along the jniLibs by renaming (implied) .exe to .so,
but it only ends up in the APK and doesn't get extracted during install to /data/data/app-name/lib .

Would be possible to package the executable as an asset and extract it manually to app cache location and set it as executable.

```Java
Context ctx = getApplicationContext();
AssetExtractor.extract(ctx.getAssets(),  ctx.getCacheDir(), "program");
File program = new File(ctx.getCacheDir(), "program");
program.setExecutable(true);
```

AssetExtractor available in https://github.com/ViliusSutkus89/pdf2htmlEX-Android/blob/master/pdf2htmlEX/src/main/java/com/viliussutkus89/android/pdf2htmlex/AssetExtractor.java

Program is generated by CMake
```CMake
add_executable(program program.cpp)
```

And manualy copying from ```app/build/intermediates/cmake/debug/obj/ABI/program``` to ```app/src/main/assets/```

I'll leave the "execute binary from Java" as an exercise to you. Test with current Android image, so that the restrictions apply. Last time I've tried that I didn't get far. If you can make that part work, I will package that method as a separate interface for this library.

**Comment by TomTasche** [comment]
I didn't realize that you actually gave the solution I suggested earlier this year a try and added comments on StackOverflow: https://stackoverflow.com/a/58748468/198996

That's what I would have tried to do myself now... I'll ask my colleague to see if he has any ideas.

**Comment by TomTasche** [comment]
@ViliusSutkus89 do you still have the code at hand you used to try the solution suggested on StackOverflow? Just found this comment that might fix the problem you've had: https://www.reddit.com/r/androiddev/comments/b2inbu/psa_android_q_blocks_executing_binaries_in_your/eitrca7/

**Comment by ViliusSutkus89** [comment]
Somehow I've missed that part, which suggested prefixing binaries with "lib".
Just tried now and older Android extracts libprogram.so just fine.
Haven't tried on Android 10, but I suspect it should work. Will test it soon.

**Comment by ViliusSutkus89** [comment]
Experimental implementation available in pdf2htmlEX-Android v0.18.11
Use the separate class `pdf2htmlEX_exe`, it extends the base class, usage is completely the same. If you want to add some extra arguments, I've exposed `Map<String, String> m_arguments` as protected member. Extend the class and stuff the parameters.
Annotated both the class and the `m_arguments` as deprecated, so that I wouldn't feel too guilty about changing the API :smiling_imp:

**Comment by TomTasche** [comment]
Looks good to me! The only concern is that you're setting LD_LIBRARY_PATH - not sure how that would work for us since we'd like to call the library from C++. Any ideas how we could avoid setting LD_LIBRARY_PATH for that purpose? @ViliusSutkus89 

For additional context: we'd like to integrate pdf2htmlEX into our existing C++ library (https://github.com/opendocument-app/OpenDocument.core) to add PDF support. That library is called via JNI (https://github.com/opendocument-app/OpenDocument.droid/blob/master/app/src/main/java/at/tomtasche/reader/background/CoreWrapper.java)

**Comment by ViliusSutkus89** [comment]
pdf2htmlEX-Android v0.18.12 addresses your `LD_LIBRARY_PATH` concerns.

`LD_LIBRARY_PATH`, which is defined at run time, is replaced by `DT_RPATH` linker flag, which does it's
work at link time. You might ask why do we even need this? Neither current working directory, nor the
directory of the executable is used by the library loaded. If the dynamic library is not placed in any
of the directories configured by `ld.conf` (`/lib`, `/usr/lib`) - your executable can't find them.

`/data/app/com.your.app/lib` is not defined in any ld.conf.

Why is this not a problem when doing JNI? Java's library loader knows that your application's
libraries are in `/data/app/com.your.app/lib`, so it looks there and EverythingJustWorks™.

To be honest, I doubt that even `LD_LIBRARY_PATH` would be a problem. It was set as an environment
variable only for the newly spawned `libpdf2htmlEX-exe_not_lib.so` process, not the main app
process that is calling `pdfh2mltEX_exe.convert()`.
`DT_RPATH` is more preferable to me, because compile / link time is nicer than run time.
Looking from the outside - result is mostly the same, except that I could remove couple of Java lines.

As for the C++ library. I don't recommend you to execute external binaries from the JNI side, because
it would involve forking. `ProcessBuilder` in Java is the way to go for that, `pdf2htmlEX_exe`
just works. You can reimplement the same functionality if you want.

If you want to do conversion from C++, it would be possible to expose [pdf2htmlEX.h](/ViliusSutkus89/pdf2htmlEX-Android/blob/library/src/pdf2htmlEX.h) from the
[pdf2htmlEX-Patch-Source-make-a-library.patch](/ViliusSutkus89/pdf2htmlEX-Android/blob/master/dependency-builder/src/main/cpp/packages/pdf2htmlEX-Patch-Source-make-a-library.patch), so you could link `OpenDocument.core` against
`libpdf2htmlEX.so` and use the C++ class `pdf2htmlEX` directly like I use it in [libpdf2htmlEX-android.so](/ViliusSutkus89/pdf2htmlEX-Android/blob/master/pdf2htmlEX/src/main/cpp/pdf2htmlEX.cc#L67).
We would still have to call Java layer to do some work.

First releases of `pdf2htmlEX-Android` were basically `pdf2htmlEX.exe` with dependencies. You may
have noticed that our wrapper (Java classes `pdf2htmlEX` and `pdf2htmlEX_exe`) grew over time and
now it provides some logic, which is needed for the library to function properly.

Here's what the wrapper does:
1) Extracts /usr/share and /etc directories for `pdf2htmlEX`, `Poppler`.
2) Extracts a couple of fonts: `Symbol`, `Zapf Dingbats`. Both are part of `pdf base 14` fonts, rarely
available on Android.
3) Extracts Fontconfig configuration files, parses `/system/etc/fonts.xml` and
`/system/etc/system_fonts.xml` to generate additional `Fontconfig` configuration.
4) Prepares environment variables that are needed for `pdf2htmlEX` or any of it's dependencies.
These environment variables are:
- HOME - used by `Fontforge`,
- TMPDIR - used by `pdf2htmlEX` and `tmpfile()` syscall,
- USER - can't recall exactly which dependency uses it, maybe Fontforge or Fontconfig,
- XDG_CACHE_HOME - used by `Fontconfig`, if I recall correctly,
- FONTCONFIG_PATH - used by `Fontconfig`.

JNI version of `pdf2htmlEX` applies these environment variables to caller's process, because it is the
same process that executes Fontforge and others, and they expect those variables to be available.
For the `pdf2htmlEX_exe`, there's no need to touch the caller's environment, only that of the newly
launched executable.

So, if we want to use lib `pdf2htmlEX` from the C++, we would still need the Java layer to do all this.

**Comment by ViliusSutkus89** [comment]
Hey,

I did some testing with `rpath` and `LD_LIBRARY_PATH` and ... bad news. `LD_LIBRARY_PATH` is here to stay.
On Linux we can set `rpath` to `$ORIGIN` and dynamic linker will look for libraries in the same folder as executable.
I thought that Bionic does this too, because it worked on few devices that I tested.
Turns out that on Android-16 that is not the case.

Tried searching and all I found was that `LD_LIBRARY_PATH` is the correct solution.
https://groups.google.com/g/android-ndk/c/CGQ701s1-AM

Moved out exe running logic to an external project - [ExecutableRunner-Android](https://github.com/ViliusSutkus89/ExecutableRunner-Android).
That project has instrumented tests, if you want to play around. `rpath` can be set in CMake using:
```CMake
SET(CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS} -Wl,-rpath='\${ORIGIN}'")
```

Closing the issue, because "it works as is", but feel free to comment :)
